import { useState } from "react";
import type { ChangeEvent } from "react";

// File generated by Copilot

interface FileUploadProps {
  /**
   * Optional callback that receives the selected file. Useful for
   * uploading to a server or passing the file up to a parent component.
   */
  onChange?: (file: File | null) => void;
}

export default function FileUpload({ onChange }: FileUploadProps) {
  const [file, setFile] = useState<File | null>(null);
  const [previewUrl, setPreviewUrl] = useState<string | null>(null);

  const handleFileChange = (e: ChangeEvent<HTMLInputElement>) => {
    const selected = e.target.files && e.target.files[0];
    if (selected) {
      setFile(selected);
      setPreviewUrl(URL.createObjectURL(selected));
      onChange && onChange(selected);
    } else {
      setFile(null);
      setPreviewUrl(null);
      onChange && onChange(null);
    }
  };

  const handleUpload = async () => {
    if (!file) return;

    // example upload logic; replace URL with your backend endpoint
    const form = new FormData();
    form.append("video", file);

    try {
      const resp = await fetch("/api/upload-video", {
        method: "POST",
        body: form,
      });
      if (!resp.ok) throw new Error("Upload failed");
      console.log("upload succeeded");
    } catch (err) {
      console.error(err);
    }
  };

  const [menuOpen, setMenuOpen] = useState(false);

  return (
    <div className="file-upload relative inline-block">
      <button
        type="button"
        onClick={() => setMenuOpen((o) => !o)}
        className="px-4 py-2 bg-blue-500 text-white rounded"
      >
        {file ? "Change file" : "Select video"}
      </button>

      {menuOpen && (
        <div className="dropdown-menu absolute z-10 bg-white border mt-1 p-2 shadow">
          <input
            id="video-upload"
            type="file"
            accept="video/mp4"
            onChange={(e) => {
              handleFileChange(e);
              setMenuOpen(false);
            }}
            className="block"
          />
          hello
        </div>
      )}

      {previewUrl && (
        <div className="preview mt-4">
          <video
            src={previewUrl}
            controls
            width={360}
            style={{ maxWidth: "100%" }}
          />
        </div>
      )}

      {file && (
        <button
          type="button"
          onClick={handleUpload}
          className="mt-4 px-4 py-2 bg-green-500 text-white rounded"
        >
          Upload
        </button>
      )}
    </div>
  );
}

