/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as ReportRouteImport } from './routes/report'
import { Route as MapRouteImport } from './routes/map'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewPotholeIdRouteImport } from './routes/review.$potholeId'
import { Route as ApiPotholesExportRouteImport } from './routes/api.potholes-export'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewPotholeIdRoute = ReviewPotholeIdRouteImport.update({
  id: '/review/$potholeId',
  path: '/review/$potholeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPotholesExportRoute = ApiPotholesExportRouteImport.update({
  id: '/api/potholes-export',
  path: '/api/potholes-export',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/map': typeof MapRoute
  '/report': typeof ReportRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/upload': typeof UploadRoute
  '/api/potholes-export': typeof ApiPotholesExportRoute
  '/review/$potholeId': typeof ReviewPotholeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/map': typeof MapRoute
  '/report': typeof ReportRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/upload': typeof UploadRoute
  '/api/potholes-export': typeof ApiPotholesExportRoute
  '/review/$potholeId': typeof ReviewPotholeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/map': typeof MapRoute
  '/report': typeof ReportRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/upload': typeof UploadRoute
  '/api/potholes-export': typeof ApiPotholesExportRoute
  '/review/$potholeId': typeof ReviewPotholeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/map'
    | '/report'
    | '/rss.xml'
    | '/upload'
    | '/api/potholes-export'
    | '/review/$potholeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/map'
    | '/report'
    | '/rss.xml'
    | '/upload'
    | '/api/potholes-export'
    | '/review/$potholeId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/map'
    | '/report'
    | '/rss.xml'
    | '/upload'
    | '/api/potholes-export'
    | '/review/$potholeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  MapRoute: typeof MapRoute
  ReportRoute: typeof ReportRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  UploadRoute: typeof UploadRoute
  ApiPotholesExportRoute: typeof ApiPotholesExportRoute
  ReviewPotholeIdRoute: typeof ReviewPotholeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$potholeId': {
      id: '/review/$potholeId'
      path: '/review/$potholeId'
      fullPath: '/review/$potholeId'
      preLoaderRoute: typeof ReviewPotholeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/potholes-export': {
      id: '/api/potholes-export'
      path: '/api/potholes-export'
      fullPath: '/api/potholes-export'
      preLoaderRoute: typeof ApiPotholesExportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  MapRoute: MapRoute,
  ReportRoute: ReportRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  UploadRoute: UploadRoute,
  ApiPotholesExportRoute: ApiPotholesExportRoute,
  ReviewPotholeIdRoute: ReviewPotholeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
